name: Publish (latest)

on:
  release:
    types: [created]

permissions:
  id-token: write

jobs:
  publish:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: npm

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - run: npm ci
      - run: npm pkg delete scripts devDependencies
      - run: npm publish --provenance --access public --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
